provider: aws

aws:
  region: ap-northeast-2
  zoneType: public
  accessKey: ""     # IAM Role 사용 시 비워둬도 됨
  secretKey: ""     # IAM Role 사용 시 비워둬도 됨

domainFilters:
  - grosmichel.click

policy: sync
overwriteExisting: true     # ✅ 기존 A 레코드 덮어쓰기 허용

registry: txt
txtOwnerId: grosmichel-eks
logLevel: debug

serviceAccount:
  create: true
  name: external-dns

rbac:
  create: true

image:
  repository: registry.k8s.io/external-dns/external-dns
  tag: v0.13.6
  pullPolicy: IfNotPresent
