apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grosmichel-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hose0504/Gros_Michel.git  # ✅ GCP 말고 AWS용 레포!
    targetRevision: HEAD
    path: Terraform/helm/static-site  # ✅ 경로도 AWS 디렉토리로
    helm:
      valueFiles:
        - values.yaml
      releaseName: grosmichel-site  # ✅ 이 줄 추가!!
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
