apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grosmichel-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hose0504/Gros_Michel.git
    targetRevision: HEAD
    path: Terraform/helm/static-site
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: static-site
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
