apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/your-repo.git
    targetRevision: HEAD
    path: static-site
  destination:
    server: https://kubernetes.default.svc
    namespace: static-site
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
