apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "static-site.fullname" . }}-ingress
  labels:
    {{- include "static-site.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: www.grosmichel.click
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /template
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
