apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "static-site.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /template
            pathType: Prefix
            backend:
              service:
                name: {{ include "static-site.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls: []
