apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: gce  # 명시 안 해도 되지만 명확히 하려면 추가
spec:
  rules:
    - host: grosmichel.click
      http:
        paths:
          - path: /template
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80
