apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "static-site.fullname" . }}
  labels:
    app: {{ include "static-site.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  cert-manager.io/cluster-issuer: letsencrypt-prod
  external-dns.alpha.kubernetes.io/hostname: www.grosmichel.click
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "static-site.fullname" . }}
                port:
                  number: 80
