apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: www.grosmichel.click
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "static-site.fullname" . }}
