replicaCount: 2

image:
  repository: jwh0722/web_v1
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: nginx
  host: www.grosmichel.click

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
