name: Terraform CI/CD

on:
  push:
    branches: ["main"]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: "ap-northeast-2"
      TF_VAR_aws_profile: "ignore-on-ci"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: cd Terraform && terraform init

      - name: Terraform Format Check
        run: cd Terraform && terraform fmt -check

      - name: Terraform Validate
        run: cd Terraform && terraform validate

      - name: Terraform Plan
        run: cd Terraform && terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: cd Terraform && terraform apply -auto-approve -var-file="terraform.tfvars"
