name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "aws/Terraform/**" # ✅ 이 경로에 변경이 생길 때만 실행됨

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: "ap-northeast-2"
      TF_VAR_aws_profile: "ignore-on-ci"

    defaults:
      run:
        working-directory: aws/Terraform # ✅ 이 디렉토리 기준으로 모든 run 명령 수행

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
