name: Terraform CI/CD for GCP

on:
  push:
    branches: ["main"] # main 브랜치에 push될 때만 실행

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_region: ${{ secrets.GCP_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        run: cd gcp && terraform init

      - name: Terraform Format Check
        run: cd gcp && terraform fmt -check

      - name: Terraform Validate
        run: cd gcp && terraform validate

      - name: Terraform Plan
        run: cd gcp && terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: cd gcp && terraform apply -auto-approve -var-file="terraform.tfvars"
