name: Terraform Destroy AWS

on:
  push:
    branches:
      - main
    # "destroy"라는 단어가 커밋 메시지에 포함된 경우에만 실행
    # 예: git commit -m "destroy: cleanup resources"
    paths:
      - "Terraform/**"

jobs:
  destroy:
    if: contains(github.event.head_commit.message, 'destroy')
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: "ap-northeast-2"
      TF_VAR_aws_profile: "ignore-on-ci"

    defaults:
      run:
        working-directory: Terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
